### ISSUE TITLE
ci: set up release automation

### ISSUE THREAD

**Issue by kopecs** [semgrep/pre-commit#1]
We still need to configure automation to ensure this repository is updated when a new release occurs.

**Comment by kopecs** [comment]
@amchiclet Were you going to be responsible for this, or who did we decide the responsible person would be?

**Comment by amchiclet** [comment]
I'm responsible for setting up some tests to use this repo for pre-commit hooks, which is separate from this issue.

I still haven't gotten a chance to discuss the best owner yet, but I would be the one who needs to initiate the discussion.
